name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  build:
    name: HHVM ${{matrix.hhvm}} - ${{matrix.os}}
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        hhvm:
          - '4.56'
          - '4.80'
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer
        run: .github/workflows/install-composer.sh --install-dir=${{runner.temp}}
      - name: Install HHVM (apt)
        if: matrix.os == 'ubuntu'
        run: |
          set -ex
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y software-properties-common apt-transport-https
          sudo apt-key add .github/workflows/hhvm.gpg.key
          if [ "${{matrix.hhvm}}" = "nightly" ]; then
            sudo add-apt-repository https://dl.hhvm.com/ubuntu
            sudo apt-get install -y hhvm-nightly
          elif [ "${{matrix.hhvm}}" = "latest" ]; then
            sudo add-apt-repository https://dl.hhvm.com/ubuntu
            sudo apt-get install -y hhvm
          else
            DISTRO=$(lsb_release --codename --short)
            sudo add-apt-repository \
              "deb https://dl.hhvm.com/ubuntu ${DISTRO}-${{matrix.hhvm}} main"
            sudo apt-get install -y hhvm
          fi
      - name: Inspect HHVM and Hack versions
        run: |
          hhvm --version
          hh_client --version
      - name: Create branch for version alias
        run: git checkout -b CI_current_pull_request
      - name: Install project dependencies
        run: php ${{runner.temp}}/composer.phar install
      - name: Typecheck
        run: hh_client
      - name: Run tests
        run: vendor/bin/hacktest tests/
      - name: Run lint
        if: matrix.hhvm != 'nightly'
        run: vendor/bin/hhast-lint
